// <auto-generated />
using System;
using CoursePlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoursePlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105193000_AddLessonContent")]
    partial class AddLessonContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

// ... (Copying relevant parts from snapshot but keeping it minimal or full? Migration designer usually has full snapshot for THAT point in time.)
// Actually, `MigrateAsync` uses the COMPILLED model mostly. The designer file is for tooling.
// The critical part is that `AppDbContextModelSnapshot` is updated so FUTURE migrations know the state.
// But for applying THIS migration, EF needs `20260105193000_AddLessonContent.cs` to exist and be compiled.
// And `AppDbContextModelSnapshot` needs to have the new column.
        }
    }
}
